# Generated by Django 5.2.7 on 2025-12-23 01:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_newuser_last_name_alter_newuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
