# Generated by Django 5.2.7 on 2025-11-24 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_collaborators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='collaborators',
        ),
    ]
