# Generated by Django 5.2.7 on 2025-10-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entry_title_alter_blog_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='new_entry', max_length=50),
        ),
    ]
