# Generated by Django 5.2.7 on 2025-12-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='about',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
