# Generated by Django 5.2.7 on 2025-10-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_author_alter_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='banner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.CharField(max_length=140),
        ),
    ]
