# Generated by Django 5.2.7 on 2025-12-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners'),
        ),
    ]
