# Generated by Django 5.2.7 on 2025-10-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_entry_banner_alter_blog_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
