# Generated by Django 5.2.7 on 2025-12-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_entry_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, upload_to='banners/'),
        ),
    ]
