# Generated by Django 5.2.7 on 2026-01-13 23:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
