# Generated by Django 5.2.7 on 2026-01-14 00:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_banner_alter_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='banner'),
        ),
    ]
