# Generated by Django 5.2.7 on 2025-12-16 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_entry_author'),
        ('collaborators', '0001_initial'),
        ('friends', '0004_alter_friendslist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', 'comentario'), ('response', 'respuesta'), ('entry', 'entrada'), ('blog', 'blog'), ('friend request', 'solicitud de amistad'), ('collab request', 'solicitud de colaboración')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollabRequestNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.basenotification')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='collaborators.collabrequest')),
            ],
            bases=('notifications.basenotification',),
        ),
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.basenotification')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='blog.entrycomment')),
            ],
            bases=('notifications.basenotification',),
        ),
        migrations.CreateModel(
            name='FriendRequestNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.basenotification')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='friends.friendrequest')),
            ],
            bases=('notifications.basenotification',),
        ),
        migrations.CreateModel(
            name='NewBlogNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.basenotification')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='blog.blog')),
            ],
            bases=('notifications.basenotification',),
        ),
        migrations.CreateModel(
            name='NewEntryNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.basenotification')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='blog.entry')),
            ],
            bases=('notifications.basenotification',),
        ),
        migrations.CreateModel(
            name='ResponseNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.basenotification')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='notifications.commentnotification')),
            ],
            bases=('notifications.basenotification',),
        ),
    ]
